---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s_csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.30.30.100
  share: /mnt/datapool/k8s_csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
