apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:MmrOzOmeWTATmf3pzy25rjtYf5wT2w4t/2apjC6/pHzPyvJwzdGp5g==,iv:tpmGBsF/ymsmw3ryHBkH+qfTzY19f+nJbsTIVO832aU=,tag:ujoP6A77BvMjRwNckUem8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sufrdqs0yn36xnvnyk3kqnd6ht7jqdvlm3uvrm7scl69wlwdycps8kglfg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2dJbnlidUdyS05KZWQ1
            bndyeGhQcWpaM1A0TFAybXFaRjlad1ZKenpRCklaYiswSno0OGFSb3RqL1FLdm5F
            MERpSGhWZC9sa2tha1QyeTlRTUtYRHcKLS0tIHpybEtRN2JiS1hmdDN5bGF1bThW
            YWYxTHFlbEF2ZitmU1d4aVBsZVc0RXMK+KaeykB6DesldB/zGs+R6UOVd6tnoz5w
            SydojiutzKJAvcAE/AL1HS0sjVAewP6QMYZc9LHnJOvZ0gFRoKjdAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T12:22:01Z"
    mac: ENC[AES256_GCM,data:IHz3pZ6a14uWP8nQCEDU4gYO2ViS2/+dvGjTVKAVOHGWKWaGbzD/XZn6BfHxCBfC2YwEXw/e6KUpnOqx1soztEbrq022QlHnnGtdInqGYkbYA9Gtu4279cY1jWJ0b9lBgCmLSu8DIvER0GowtBAwvOpCdarLEJxo9rHIhzrGMfY=,iv:LVgnPDZliGQKFGjpWce5BJr7mg6Pd0L82YLKN3NQxSM=,tag:GKPacZ2Hw5DNkp5XDlDmsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
